services:
  postgres:
    image: postgres:16-alpine
    container_name: ticketing-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ticketing-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex




  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ticketing-rabbitmq
    restart: always
    ports:
      - "5672:5672"    # AMQP protocol — your app connects here
      - "15672:15672"  # Management UI — browser dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
 


  api:
    build: .
    container_name: ticketing-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password@postgres:5432/ticketing
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  

volumes:
  pgdata: